export const users = [
    { username: "user1", department: "Computer Science", semester: "1st" },
    { username: "user2", department: "Electrical Engineering", semester: "2nd" },
    { username: "user3", department: "Mechanical Engineering", semester: "3rd" },
    { username: "user4", department: "Business Administration", semester: "4th" },
    { username: "user5", department: "Biotechnology", semester: "5th" },
    { username: "user6", department: "Computer Science", semester: "6th" },
    { username: "user7", department: "Electrical Engineering", semester: "7th" },
    { username: "user8", department: "Mechanical Engineering", semester: "8th" },
    { username: "user9", department: "Business Administration", semester: "1st" },
    { username: "user10", department: "Biotechnology", semester: "2nd" },
    { username: "user11", department: "Computer Science", semester: "3rd" },
    { username: "user12", department: "Electrical Engineering", semester: "4th" },
    { username: "user13", department: "Mechanical Engineering", semester: "5th" },
    { username: "user14", department: "Business Administration", semester: "6th" },
    { username: "user15", department: "Biotechnology", semester: "7th" },
    { username: "user16", department: "Computer Science", semester: "8th" },
    { username: "user17", department: "Electrical Engineering", semester: "1st" },
    { username: "user18", department: "Mechanical Engineering", semester: "2nd" },
    { username: "user19", department: "Business Administration", semester: "3rd" },
    { username: "user20", department: "Biotechnology", semester: "4th" },
    { username: "user21", department: "Computer Science", semester: "5th" },
    { username: "user22", department: "Electrical Engineering", semester: "6th" },
    { username: "user23", department: "Mechanical Engineering", semester: "7th" },
    { username: "user24", department: "Business Administration", semester: "8th" },
    { username: "user25", department: "Biotechnology", semester: "1st" },
    { username: "user26", department: "Computer Science", semester: "2nd" },
    { username: "user27", department: "Electrical Engineering", semester: "3rd" },
    { username: "user28", department: "Mechanical Engineering", semester: "4th" },
    { username: "user29", department: "Business Administration", semester: "5th" },
    { username: "user30", department: "Biotechnology", semester: "6th" },
    { username: "user31", department: "Computer Science", semester: "7th" },
    { username: "user32", department: "Electrical Engineering", semester: "8th" },
    { username: "user33", department: "Mechanical Engineering", semester: "1st" },
    { username: "user34", department: "Business Administration", semester: "2nd" },
    { username: "user35", department: "Biotechnology", semester: "3rd" },
    { username: "user36", department: "Computer Science", semester: "4th" },
    { username: "user37", department: "Electrical Engineering", semester: "5th" },
    { username: "user38", department: "Mechanical Engineering", semester: "6th" },
    { username: "user39", department: "Business Administration", semester: "7th" },
    { username: "user40", department: "Biotechnology", semester: "8th" },
    { username: "user41", department: "Computer Science", semester: "1st" },
    { username: "user42", department: "Electrical Engineering", semester: "2nd" },
    { username: "user43", department: "Mechanical Engineering", semester: "3rd" },
    { username: "user44", department: "Business Administration", semester: "4th" },
    { username: "user45", department: "Biotechnology", semester: "5th" },
    { username: "user46", department: "Computer Science", semester: "6th" },
    { username: "user47", department: "Electrical Engineering", semester: "7th" },
    { username: "user48", department: "Mechanical Engineering", semester: "8th" },
    { username: "user49", department: "Business Administration", semester: "1st" },
    { username: "user50", department: "Biotechnology", semester: "2nd" },
    { username: "user51", department: "Computer Science", semester: "3rd" },
    { username: "user52", department: "Electrical Engineering", semester: "4th" },
    { username: "user53", department: "Mechanical Engineering", semester: "5th" },
    { username: "user54", department: "Business Administration", semester: "6th" },
    { username: "user55", department: "Biotechnology", semester: "7th" },
    { username: "user56", department: "Computer Science", semester: "8th" },
    { username: "user57", department: "Electrical Engineering", semester: "1st" },
    { username: "user58", department: "Mechanical Engineering", semester: "2nd" },
    { username: "user59", department: "Business Administration", semester: "3rd" },
    { username: "user60", department: "Biotechnology", semester: "4th" }
  ];
  

  